# SwiftLint Configuration for MapChat
# Enforces clean code with strict limits

# Paths to include/exclude
included:
  - MapChat
  - Packages

excluded:
  - Pods
  - Carthage
  - DerivedData
  - .build
  - "**/Tests"

# File length limits
file_length:
  warning: 400
  error: 450
  ignore_comment_only_lines: true

# Type body length
type_body_length:
  warning: 350
  error: 400

# Function body length
function_body_length:
  warning: 50
  error: 100

# Line length
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 15

# Nesting
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Identifier naming
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

# Force unwrapping
force_unwrapping: error

# Force try
force_try: error

# Implicit getter
implicit_getter: warning

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: false

# Trailing comma
trailing_comma:
  mandatory_comma: true

# Disabled rules
disabled_rules:
  - todo # We'll track todos separately
  - identifier_name # Allow short names where contextually clear

# Opt-in rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Reporter
reporter: "xcode"
